### ISSUE TITLE
Telemetry compatibility

### ISSUE THREAD

**Issue by Cantido** [mtrudel/bandit#105]
It looks like a lot of the telemetry in Bandit doesn't follow the pattern that [`:telemetry.span/3`](https://hexdocs.pm/telemetry/telemetry.html#span/3) sets. Why don't you use `:telemetry.span/3`? It handles some of the work you're doing yourself in Bandit, like creating span contexts and adding timestamps and durations. There are also some libraries that adapt telemetry to other protocols, and they expect data in the style of `span/3`. In particular, I'm thinking of the [OpenTelemetry adapter library](https://github.com/open-telemetry/opentelemetry-erlang-contrib/tree/main/utilities/opentelemetry_telemetry) that turns telemetry spans into OpenTelemetry data.

**Comment by mtrudel** [comment]
Path dependency, mostly. I based Bandit's telemetry work on the work in Thousand Island, which started off as an opinionated span implementation I'd intended to eventually spin out into a separate library and subsequently walked back some of those opinions, ending up with the scope where it is now. I supposed that where things ended up, it might make more sense to refactor this to use the more idiomatic patterns provided by `:telemetry.span/3` et al. Let me tinker with this a bit and see if it's easier to work with. 

In terms of Otel integration, I'd talked to @bryannaegele early in the implementation (and indeed, his input was what toned down a lot of my stronger opinions on how to approach this) but haven't run the current implementation by him or anyone else on that team.

Thanks for the note!

**Comment by Cantido** [comment]
Sure thing, I totally understand! I actually saw some of that conversation as I was browsing the Otel issue tracker recently. I was hoping to contribute an Otel instrumentation for Bandit someday since I really appreciate this project and your goals for it, and that's when I started digging into the code here.

Is there anything I could do to help out? I was thinking of doing some of my own tinkering to use `span` and submitting a PR, but I know that telemetry integration is one of your focuses for this version, and I didn't want to get in your way.

**Comment by mtrudel** [comment]
The main opinion I was trying to emphasize when I was working up the original implementation of telemetry in Thousand Island (which as above, is basically the direct ancestor of the work in Bandit) was that I wanted to have instrumentation have as little effect on the pre-existing code as possible. That was really the main reason I didn't use `:telemetry.span/3` as an implementation, since it required work to be done within a singular function. This was problematic for two reasons:

1. I really don't like how the pattern of wrapper functions like `:telemetry.span/3` (or Ecto's transaction functions, as another examples) require you to adapt how you structure your code to fit their needs. Part of it is what it does to code locality (having to move things into/out of an arbitrary functional nesting), part of it is diff-based (introducing telemetry induces a giant diff that does nothing other than indent your code), and part of it is just aesthetic

2. A *lot* of the work in Thousand Island / Bandit takes place in a coordinated manner between processes / discrete messages, and it's just not possible to be able to capture a complete telemetry span within a single function in the manner that `:telemetry.span/3` expects. There are numerous places where a span starts in (say) an `init/1` call and ends in a `terminate/3` call a short time later. Such is the life of async code such as a network server. 

What I settled on was a context-based approach, where `start` calls both emit a start event, and also return an opaque span context that is subsequently passed into `stop` calls to emit matching stop / exception events. This replaces the functional wrapper approach of `:telemetry.span/3` with a data-based approach where all the library needs to do is to track the context structure for the duration of a span, resulting in:

1. Less changes required to existing code, since nothing about their structure needs to change. The idealized diff in this case will literally just be the `start` and `stop` calls as appropriate.
2. An easy ability to transact spans across process / message boundaries. You can trivially start a span in an `init/1` call and stop it in a `terminate/3` call simply by passing the span context around in your GenServer state.
3. No *strictly required* changes to the structure of the emitted events.

The main opinion I was trying to emphasize when I was working up the original implementation of telemetry in Thousand Island (which as above, is basically the direct ancestor of the work in Bandit) was that I wanted to have instrumentation have as little effect on the pre-existing code as possible. That was really the main reason I didn't use `:telemetry.span/3` as an implementation, since it required work to be done within a singular function. This was problematic for two reasons:

1. I really don't like how the pattern of wrapper functions like `:telemetry.span/3` (or Ecto's transaction functions, as another examples) require you to adapt how you structure your code to fit their needs. Part of it is what it does to code locality (having to move things into/out of an arbitrary functional nesting), part of it is diff-based (introducing telemetry induces a giant diff that does nothing other than indent your code), and part of it is just aesthetic

2. A *lot* of the work in Thousand Island / Bandit takes place in a coordinated manner between processes / discrete messages, and it's just not possible to be able to capture a complete telemetry span within a single function in the manner that `:telemetry.span/3` expects. There are numerous places where a span starts in (say) an `init/1` call and ends in a `terminate/3` call a short time later. Such is the life of async code such as a network server. 

What I settled on was a context-based approach, where `start` calls both emit a start event, and also return an opaque span context that is subsequently passed into `stop` calls to emit matching stop / exception events. This replaces the functional wrapper approach of `:telemetry.span/3` with a data-based approach where all the library needs to do is to track the context structure for the duration of a span, resulting in:

1. Less changes required to existing code, since nothing about their structure needs to change. The idealized diff in this case will literally just be the `start` and `stop` calls as appropriate.
2. An easy ability to transact spans across process / message boundaries. You can trivially start a span in an `init/1` call and stop it in a `terminate/3` call simply by passing the span context around in your GenServer state
3. No *strictly required* changes to the structure of the emitted events

I feel pretty strongly that points 1 and 2 above are sufficient justification for the approach taken here (at least structurally). I don't think we should be replacing this implementation with `:telemetry.span/3` calls as they simply don't map onto how Thousand Island & Bandit *need* telemetry to work. 

In terms of how to possibly help out, what I *do* think we can definitely do here to is improve point 3 above (that is, ensure that the events we emit are as close as possible in structure and naming to those in `:telemetry.span/3` (on the understanding that it codifies best practices for this). If you're up for it, *that* is work I'd be happy to see done. 

To accomplish this, I think the majority (if not the entirety) of the work would be isolated in `Bandit.Telemetry` and how it structures the events it builds (along with updates to the existing test coverage, of course). The structure of the emitted events is also documented in the ex_doc at the top of that module.

I've been trying to keep the implementation of `Bandit.Telemetry` in sync with that in `ThousandIsland.Telemetry`, so updates there would be welcome as well! FWIW, the implementation in these modules was what I was intending to eventually spin out into a separate library that provided an opinionated set of (macro based) helpers to provide context-based telemetry support, along with automated documentation generation. You can see a *really* early spike of that work at https://github.com/mtrudel/thousand_island/commit/0826af2a532fe14c98529c4705027071ef9365f3

**Comment by mtrudel** [comment]
Yep, exactly! Feel like taking it on?

**Comment by Cantido** [comment]
I can certainly try!

**Comment by mtrudel** [comment]
@Cantido any progress? I've got a couple of free days later this week that I can tackle this but I don't want to step on your toes if you're making progress. LMK!

**Comment by mtrudel** [comment]
Closing since corresponding work is complete!
