### ISSUE TITLE
shutdown_timeout is not accepted

### ISSUE THREAD

**Issue by jbernardo95** [mtrudel/bandit#125]
When passing `shutdown_timeout` as an option Bandit refuses to start with the following error message:

```
Unsupported keys(s) in options config: [:shutdown_timeout]
```

After a quick search through the code the only reference to `:shutdown_timeout` is in the docs. It doesn't seem to be used for anything in practice.

Is this still not implemented?

**Comment by mtrudel** [comment]
`shutdown_timeout` is an underlying Thousand Island concern, implemented [here](https://github.com/mtrudel/thousand_island/commit/76047472d4421a234b9309efba03af3ea7514b61). The issue you identified is that Bandit wasn't passing the option through to Thousand Island. 

This has been fixed in `0.7.5`, just released. 

Thanks for the issue!

**Comment by jbernardo95** [comment]
Great, thank you!
