### ISSUE TITLE
Header timestamp couldn't be fetched from ETS cache

### ISSUE THREAD

**Issue by zoedsoupe** [mtrudel/bandit#187]
Good job folks! It's really nice to see works like this in the Elixir ecosystem!

So, I converted my phoenix application to an umbrella project, and started to create some additional `Endpoints` and also a "proxy" app to redirect requests to the corresponding internal server.

Then, whenever I start my web server, I receive this warning now:

```
[warning] Header timestamp couldn't be fetched from ETS cache
```

Digging into the log metadata I discovered that this was the module: `Bandit.Clock`. The complete log can be found below:

```
08:46:25.874 erl_level=warning application=bandit domain=elixir file=lib/bandit/clock.ex function=date_header/0 line=23 mfa=Bandit.Clock.date_header/0 module=Bandit.Clock pid=<0.1273.0> request_id=F2wy9HLOhtbXOI0AAACn [warning] Header timestamp couldn't be fetched from ETS cache
```

Looking at this module, this warning log is working as expected, so my doubt is: why exactly is this being triggered and how can I suppress/solve this issue?

My project can be found [here](https://github.com/peapescarte/pescarte-plataforma), as I couldn't reproduce this warning into a fresh new application... Also I created an [Elixir forum thread](https://elixirforum.com/t/warning-about-missing-value-in-ets-table/56694/2) about it.

**Comment by mtrudel** [comment]
Thanks for the issue!

The error message you're seeing isn't supposed to happen in normal execution; it's an indication that your Bandit connection processes (the ones that actually serve requests from clients) aren't able to find the current time in the ETS cache (for performance reasons, we use an ETS cached version of the current time for return in `Date` headers since formatting a date is a relatively expensive operation. The `Bandit.Clock` process is responsible for updating this value once per second). The problem in your case is that the `Bandit.Clock` process hasn't started by the time your Phoenix processes (and thus your Bandit request processes) have started, and so the ETS cache is empty when your Bandit request process go looking there (this isn't a client-visible error, since Bandit's fallback is to [compute them in-process](https://github.com/mtrudel/bandit/blob/main/lib/bandit/clock.ex#L24). It's just very inefficient).  

This is happening in your case because you haven't expressed your dependency on bandit in the correct place. You've put it in your top-level mix file, whereas your phoenix dependencies are in your child apps. This is putting you in a situation where your Phoenix processes start before your Bandit one does. 

You should be able to solve this by moving your bandit dependency alongside your phoenix dependencies inside your child apps. As with your phoenix dependencies,  you can (and should!) duplicate these dependencies in every application that actually makes use of Bandit.

**Comment by zoedsoupe** [comment]
Oh, thanks for this complete explanation! Indeed I made a confusion about "global deps".
