### ISSUE TITLE
Plug.Conn being created with remote_ip as local?

### ISSUE THREAD

**Issue by jimc64** [mtrudel/bandit#227]
hi!

https://github.com/mtrudel/bandit/blob/26900d097c35741430c30b6b7fae68c5e3451fd2/lib/bandit/pipeline.ex#L42

I've tried switching Phoenix recently to use Bandit (and am loving it), but I noticed that the remote IP address in my access logs are now showing as my local address, rather than the actual remote/peer address.

I think this is the culprit -- here in build_conn(), should `sockname` instead be `peername`?

**Comment by mtrudel** [comment]
Yep, that is indeed the culprit; looks like I [introduced this](https://github.com/mtrudel/bandit/commit/b126f3af6ebc8c0fd6e18f1eb1aa57e86250ac08#diff-68626306df11d3e10964941997c6cdafbf587a9ec7de087141840655a47a1855R42) a few months ago during a refactor. I don't really see a clear way to get this under test since both the peer and local are localhost, but I'll figure something out.

In the meantime this is fixed in b3a0552 and released in 1.0.0-pre.15. Thanks for the bug!

**Comment by jimc64** [comment]
Thanks for the quick fix! (And yes, I'm also curious to see how to address it in tests, without resorting to something heavy like a multi-host docker-compose sandbox, etc.)
