### ISSUE TITLE
gzip compressed requests

### ISSUE THREAD

**Issue by saleyn** [mtrudel/bandit#316]
Does Bandit support gzip compressed HTTP/1.1 requests?  As far as I can tell from the code it handles compression of the response if `Accept-Encoding: gzip` is set, but it doesn't handle the decompression of incoming compressed payload (`Content-Encoding: gzip`).  Am I missing something?

**Comment by mtrudel** [comment]
Correct. It's generally much less common to compress uploads, since negotiation requires either an assumption of server support, or negotiation via 100 response codes. As a result it didn't make the first cut of compression support in Bandit. Once the refactors in #297 et al land, we'll be in a much better position to add semantic levels things such as this, and I expect to do so.

**Comment by saleyn** [comment]
I have cases when HTTP clients send gzip compressed requests...  Any tentative timeline on adding this feature?

**Comment by mtrudel** [comment]
Likely a few months out. I was hoping to land #297 et al already, but keeping up with bugfixes and miscellaneous stuff from becoming phoenix's default has taken up a ton of time lately so I'm a bit behind schedule.

**Comment by mtrudel** [comment]
Added to my internal planning list. Again, this is likely going to be a few months out; a bunch of other stuff such as #297 et al need to land first. I'll report back here when it lands.

**Comment by mtrudel** [comment]
Closing for hygiene.
