### ISSUE TITLE
Consider sticking to semantic versioning

### ISSUE THREAD

**Issue by jozuas** [mtrudel/bandit#367]
While it is not my business managing this project, I think it would be nice to consider sticking to [semantic versioning](https://semver.org/) scheme.

Today I got a bit surprised when I did `mix deps.update --all `:
<img width="268" alt="image" src="https://github.com/mtrudel/bandit/assets/13085275/d066599c-0660-490c-9671-639ac7ae15da">

And found out that a minor `bandit` version 1.4.1 introduced breaking changes:
<img width="1114" alt="image" src="https://github.com/mtrudel/bandit/assets/13085275/4b826034-6857-4bca-8803-563ba0e6ffd7">

**Comment by mtrudel** [comment]
Thanks for the note. I appreciate the perspective; these changes were ones that I thought long and hard about, and that we had a number of internal discussions about as well. The answer basically amounts to 'maintenance burden'. Allow me to explain:

If we were to have honoured semver for this change, we'd have had to cut a 2.0.0 release, which would have meant that anyone pinning to `~> 1.0` would have had to take explicit action to pull in this new version. At the same time, the *vast* majority of our usage is within Phoenix projects. The way Phoenix generates applications means that essentially all of our users are in fact pinned to `~> 1.0` in this exact way.

Experience seems to suggest that the majority of users don't do *anything* with most of their dependencies. If Phoenix generated a `mix.exs` file that was pinned as above, the likelihood is that it would stay that way forever. And so, we'd be in a position where we'd have two options:

1. Let the 1.0 release tree rot, and deny the vast majority of our user base any future improvements, or;
2. Carry out new work against both 1.0 and 2.0 trees for the rest of time

On balance, there is no scenario in which either of these is a reasonable tradeoff for something as small as a config option & a few telemetry changes (not to mention, a config option that was only introduced in a minor release a few months prior).

Moreover, we maintain a ruthlessly detailed CHANGELOG that is updated on *every* release, and is literally the first thing I point to when I publicize releases (if you're not already a member, you should join the #bandit Elixir slack channel where we announce every release, alongside such a link). Breaking changes (which, to be clear, we go to **great lengths** to avoid) are *always* called out prominently.

It's also worth noting that the project has never claimed to conform to semver; there has never been a mention of it in the README or elsewhere, and even personally I've never felt a need to bound myself to such a restrictive yoke. To be clear, I cannot and will not promise to not violate semver in the future, though I will continue to do my best to adhere to its spirit.

But ultimately, and with the *utmost* respect, I think you're expecting too much of maintainers. None of us work for you, and there isn't a project in the world that owes you conformance to semver. The reality of this or any endeavour (technological or otherwise) is compromise. Semver is, in many real and tangible ways, a bit of a prison for maintainers in that sense. It presumes a world where users (and other package maintainers with transitive dependencies) move fast, are hyper aware of their dependencies, and know the pedigree and development direction of everything in their deps folder. This, unfortunately, does not map to reality in any meaningful way. If we as a community are going to make this grand experiment work in a sustainable way, there needs to be some concession and adaptability on the part of users.

Turning back to the prescriptive aspects of your situation, you may want to look at the changes that just came out in 1.5.3 with the `log_protocol_errors` option. It now provides (and defaults to) a value of `:short`, which will cause one-line summaries of protocol errors to be logged. Moreover, I'll note that this is actually one of the more actively developed corners of the project at this point (a lot of people have a lot of opinions on how logging should work), so I can't promise it won't change again in the future (though I have no open plans for it to do so). 

Thanks again for the discussion.

**Comment by ryanwinchester** [comment]
RomVer best versioning 

https://github.com/romversioning/romver

**Comment by jozuas** [comment]
Thank you for such an insightful and detailed answer.

And thank you for such a great project.
